name: Github build

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '20', '22']
    name: Node ${{ matrix.node }}

    steps:
      - uses: actions/checkout@v2
      - name: Setup node js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: npm install -g npm@9
      - run: npm install
      - run: npm run compile
      - run: npm run compile:db
      - run: npm run test