import 'package:flutter/foundation.dart';
import '../models/course.dart';

class CourseProvider with ChangeNotifier {
  final List<Course> _courses = [
    Course(
      id: 1,
      title: 'Flutter for Beginners',
      description: 'Learn to build mobile apps using Flutter.',
      subtitle: 'Build Mobile App', 
      lessons: 12,
      progress: 0.35,
      category: 'Writing', 
      accentHex: 'B3E5FC',
      videoAsset: 'assets/videos/mov_bbb.mp4',
    ),
    Course(
      id: 2,
      title: 'Advanced Dart',
      subtitle: 'Advanced Dart', 
      description: 'Deep dive into Dart programming language.',
      lessons: 8,
      progress: 0.6,
      category: 'Writing', 
      accentHex: 'B3E5FC',
      videoAsset: 'assets/videos/sample_video_placeholder.txt',
    ),
    Course(
      id: 3, 
      title: 'Application Essay Mastery',
      description: 'Application Essay Mastery.', 
      subtitle: 'Structure & storytelling', 
      progress: 0.34, 
      lessons: 9, 
      category: 'Writing', 
      accentHex: 'B3E5FC',
      videoAsset: 'assets/videos/mov_bbb.mp4',
    ),
    Course(
      id: 4, 
      title: 'Study Planner', 
      description: 'Weekly & monthly plans study planner.',
      subtitle: 'Weekly & monthly plans', 
      progress: 0.72, 
      lessons: 6, 
      category: 'Productivity', 
      accentHex: 'E1F5D9',
      videoAsset: 'assets/videos/mov_bbb.mp4',
    ),
    Course(
      id: 5, 
      title: 'Test Prep: Math',
      description: 'Deep dive into Mathematics.', 
      subtitle: 'Key strategies & drills', 
      progress: 0.18, 
      lessons: 14, 
      category: 'Test Prep', 
      accentHex: 'FFF3CC',
      videoAsset: 'assets/videos/mov_bbb.mp4',
    ),
    Course(
      id: 6, 
      title: 'Scholarship Applications',
      description: 'Find & apply to Scholarship Applications.', 
      subtitle: 'Find & apply', 
      progress: 0.52, 
      lessons: 7, 
      category: 'Applications', 
      accentHex: 'F0E5FF',
      videoAsset: 'assets/videos/mov_bbb.mp4',
    ),
    Course(
      id: 7, 
      title: 'Interview Practice',
      description: 'Mock interviews & tips.', 
      subtitle: 'Mock interviews & tips', 
      progress: 0.06, 
      lessons: 4, 
      category: 'Career', 
      accentHex: 'FFEAE6',
      videoAsset: 'assets/videos/mov_bbb.mp4',
    ),
  ];

  List<Course> get courses => _courses;
}
