// Auto-generated by generate-pages-wrapper.js
import React from "react";
import Component from "../src/pages/About.jsx";

export { Page }
export const documentProps = {
  title: "About | Apply4Study",
  description: "About page"
};

function Page() {
  return <Component />;
}
