// Auto-generated by generate-pages-wrapper.js
import React from "react";
import Component from "../src/pages/Blog.jsx";

export { Page }
export const documentProps = {
  title: "Blog | Apply4Study",
  description: "Blog page"
};

function Page() {
  return <Component />;
}
