// Auto-generated by generate-pages-wrapper.js
import React from "react";
import Component from "../src/pages/Contact.jsx";

export { Page }
export const documentProps = {
  title: "Contact | Apply4Study",
  description: "Contact page"
};

function Page() {
  return <Component />;
}
