// Auto-generated by generate-pages-wrapper.js
import React from "react";
import Component from "../src/pages/Courses.jsx";

export { Page }
export const documentProps = {
  title: "Courses | Apply4Study",
  description: "Courses page"
};

function Page() {
  return <Component />;
}
