// Auto-generated by generate-pages-wrapper.js
import React from "react";
import Component from "../src/pages/getStarted.jsx";

export { Page }
export const documentProps = {
  title: "getStarted | Apply4Study",
  description: "getStarted page"
};

function Page() {
  return <Component />;
}
