// Auto-generated by generate-pages-wrapper.js
import React from "react";
import Component from "../src/pages/Home.jsx";

export { Page }
export const documentProps = {
  title: "Home | Apply4Study",
  description: "Home page"
};

function Page() {
  return <Component />;
}
