// Auto-generated by generate-pages-wrapper.js
import React from "react";
import Component from "../src/pages/Partners.jsx";

export { Page }
export const documentProps = {
  title: "Partners | Apply4Study",
  description: "Partners page"
};

function Page() {
  return <Component />;
}
