// Auto-generated by generate-pages-wrapper.js
import React from "react";
import Component from "../src/pages/Price.jsx";

export { Page }
export const documentProps = {
  title: "Price | Apply4Study",
  description: "Price page"
};

function Page() {
  return <Component />;
}
