// Auto-generated by generate-pages-wrapper.js
import React from "react";
import Component from "../src/pages/PrivacyPolicy.jsx";

export { Page }
export const documentProps = {
  title: "PrivacyPolicy | Apply4Study",
  description: "PrivacyPolicy page"
};

function Page() {
  return <Component />;
}
