// Auto-generated by generate-pages-wrapper.js
import React from "react";
import Component from "../src/pages/Python.jsx";

export { Page }
export const documentProps = {
  title: "Python | Apply4Study",
  description: "Python page"
};

function Page() {
  return <Component />;
}
