// Auto-generated by generate-pages-wrapper.js
import React from "react";
import Component from "../src/pages/RefundPolicy.jsx";

export { Page }
export const documentProps = {
  title: "RefundPolicy | Apply4Study",
  description: "RefundPolicy page"
};

function Page() {
  return <Component />;
}
