// Auto-generated by generate-pages-wrapper.js
import React from "react";
import Component from "../src/pages/SearchResults.jsx";

export { Page }
export const documentProps = {
  title: "SearchResults | Apply4Study",
  description: "SearchResults page"
};

function Page() {
  return <Component />;
}
