// Auto-generated by generate-pages-wrapper.js
import React from "react";
import Component from "../src/pages/Services.jsx";

export { Page }
export const documentProps = {
  title: "Services | Apply4Study",
  description: "Services page"
};

function Page() {
  return <Component />;
}
