// Auto-generated by generate-pages-wrapper.js
import React from "react";
import Component from "../src/pages/Services.jsx";

// Route used by Vike
export const route = "/services";

// documentProps for Vike
export const documentProps = {
  title: {
    default: "Services",
    template: "%s — Apply4Study",
    config: {}
  },
  description: {
    default: "Services page",
    config: {}
  }
};

// ✅ V1-compatible default export
export default {
  Page: Component,
  route,
  documentProps
};
