// Auto-generated by generate-pages-wrapper.js
import React from "react";
import Component from "../src/pages/ShippingPolicy.jsx";

export { Page }
export const documentProps = {
  title: "ShippingPolicy | Apply4Study",
  description: "ShippingPolicy page"
};

function Page() {
  return <Component />;
}
