// Auto-generated by generate-pages-wrapper.js
import React from "react";
import Component from "../src/pages/TermsConditions.jsx";

export { Page }
export const documentProps = {
  title: "TermsConditions | Apply4Study",
  description: "TermsConditions page"
};

function Page() {
  return <Component />;
}
